import {readFile, access} from 'node:fs/promises';
const files=['index.html','src/main.js','src/component.js','src/db.js','src/schema.js','src/catalog.js','src/pdf.js','src/ai.js','src/transformers-runtime.js','src/transformers-worker.js','public/sw.js','public/manifest.webmanifest'];
for(const file of files) await access(file);
const component=await readFile('src/component.js','utf8');
const main=await readFile('src/main.js','utf8');
if(!component.includes('Component.call(context, props)')) throw new Error('Binder Static Next ausente.');
if(!main.includes('function* App')) throw new Error('Componente generator principal ausente.');
if(!main.includes('Object.assign(this.state,yield')) throw new Error('Protocolo next(patch) ausente.');
JSON.parse(await readFile('public/manifest.webmanifest','utf8'));
JSON.parse(await readFile('public/app-config.json','utf8'));
console.log('Estrutura PWA, JSON e contrato Static Next validados.');
